### ISSUE TITLE
document formatter step

### ISSUE THREAD

**Issue by JDziurlaj** [xproc/Vnext#33]
Add a step that would format the source according to a implementation-defined algorithm for the document type. By default this would function as a pretty-printer, but could also be used to strip whitespace (in accordance with `xml:space`)

**Comment by xml-project** [comment]
I am not sure I understand the difference between the proposed step and `<p:cast-content-type content-type="text/plain" />`.
@JDziurlaj  Could you please elaborate the purpose of your proposal a bit more.

**Comment by JDziurlaj** [comment]
This is not to parse input, but to reformat it so it is easier for downstream consumers (specifically humans). For an XML example, to make `<a><b><c>afs</c></b></a>` become

```xml
<a>
	<b>
		<c>afs</c>
	</b>
</a>
```
or similar.

**Comment by xml-project** [comment]
Sorry for being not precise. I was not talking about parsing, but about serializing the doc. I think the following pipeline will produce the result in your example.
````
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" name="pipeline" version="3.0">
    <p:output port="result" />
    <p:identity>
        <p:with-input><a><b><c>afs</c></b></a></p:with-input>
    </p:identity>
    <!-- Let's may it pretty -->
    <p:set-properties properties="map{'serialization' : map {'indent' : true()}}" />
    <p:cast-content-type content-type="text/plain" /> <!-- Now its a serialized text document -->
    <p:cast-content-type content-type="application/xml" /> <!-- So we need to parse it -->
</p:declare-step>
````
