### ISSUE TITLE
Problems with XPath-Version

### ISSUE THREAD

**Issue by xml-project** [xproc/Vnext#39]
After playing around with the upcoming XPath 4.0 a bit, I think I found two minor problems with [XPath versioning in XProc 3.0](https://spec.xproc.org/3.0/xproc/#declare-pipelines):

> The requested xpath-version must be used to evaluate XPath expressions subject to the constraints outlined in [Section 7.2.2, “XPath in XProc”](https://spec.xproc.org/3.0/xproc/#xpath-context). If the attribute is not specified, the value “3.1” is assumed. It is a [static error](https://spec.xproc.org/3.0/xproc/#dt-static-error) ([err:XS0110](https://spec.xproc.org/3.0/xproc/#err.S0110)) if the requested XPath version is less than “3.1”.

1. To me it is not clear what a processor is expected to do, if @xpath-version="4.0" is requested, but this version is not supported. There is only an error mentioned for a version less than "3.1". What error is expected here? To me the first sentence mean, that a processor is not allowed to silently use 3.1. Do we need another static error code or do we change XS0110 to a general XPath not supported?
2. The XPath version is to my understanding not inherited from an ancestor. I think this is not a good solution because if I declare different steps in a library I have to set XPath version explicitly for every step. The proposal is add an inheritance mechanism as we have for the XProc version.
What did I miss?

**Comment by ndw** [comment]
Resolved by https://github.com/xproc/3.0-specification/pull/1092
